### PR TITLE
Added support for X-Forwarded-For headers to detect original client IP

### PR DESCRIPTION
**Pull request by leeprovoost**
As per our discussion here https://github.com/meatballhat/negroni-logrus/issues/25

### CODE REVIEW

**Comment by gravis** [comment]
The only issue I see with the current is that `remoteAddr` is not an IP any more, it's a string containing one or more IPs. 
Moreover, we don't control anything in the header `X-Forwarded-For`, so spoofing IPs (at least for logging) in programs using negroni-logrus would be doable with this PR.

I think we think improve this code a bit before merging, as I smell some security issues regarding to the last point.
For example, Rails is using an array of [trusted proxies](https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L33) and will log only ONE ip. I think this is (really) important.

@meatballhat, do you have an opinion on this please?

**Comment by gravis** [comment]
Just to be clear: we definitively need this PR.
I just want to make sure we not doing this change too fast, as it will impact users a lot.

**Comment by leeprovoost** [comment]
I like the trusted proxy concept. I guess we could benefit from the research that the rails community has done and copy their default list, but also allow a user to add their own entries to be merged into this list.

This will be a much bigger piece of work though to implement some sort of IP filter taking in account things like regexp, network masks, etc.

However, it still means though that we can't guarantee that the remoteAddr will ALWAYS be a single IP address. This will depend on whether someone has correctly supplied all their IP address ranges / CIDRs. 

I still think though that this shouldn't be the responsibility of this package. This package should just write logs. I'd leave it up to the user to implement other middleware in negroni that takes care of this, because this is not just a problem for this logging package, but for everything that uses negroni and reasons about IP addresses. BTW saw that some people already built middleware: https://github.com/sebest/xff

**Comment by gravis** [comment]
Sounds good to me. Let's use https://github.com/sebest/xff, and fix the test suite.
Could you do that?
Thanks :)

**Comment by gravis** [comment]
Forget my last comment, xff is a middleware, so it should be part of another middleware.
I took at xff, and it's already taking care of this for us.
The only drawback is the lack of "X-Real-IP" header, but it's something to take care of in the other middleware I think, "not our business" as your said.
I think this makes this MR obsolete, what do you think?

**Comment by gravis** [comment]
See sebest/xff#6 also

**Comment by meatballhat** [comment]
:sob: closing, but happy to reopen if desired

**Pull request closed without merging**
