### PR TITLE
Method to create new middleware with a given logrus instance.

### PR DESCRIPTION
**Pull request by dbalan**
This helps re-using existing logger instance.

### CODE REVIEW

**Comment by alecha** [comment]
+1

**Comment by meatballhat** [comment]
@dbalan Thanks for the PR!  This is the intent with `Logger` being a public struct member, as @jszwedko describes in #10.  I don't expect to be able to predict how everyone wants to use this library.  That being said, I totally get wanting a method to formalize this use case :smiley_cat:.  I have one nitpick: Can the func have this name and signature instead?

``` go
func NewMiddlewareFromLogger(logger *logrus.Logger, name string) *Middleware {
// ...
}
```

**Comment by dbalan** [comment]
@meatballhat done!

**Comment by meatballhat** [comment]
@dbalan Thank you! :metal:

**Pull request merged**
