### PR TITLE
Update imports of codegangsta/negroni to point to urfave/negroni

### LINKED ISSUE #22: Support of urfave/negroni
Hello,

Do you plan to support the codegansta/negroni migration to urfave/negroni ?

Regards.

### PR DESCRIPTION
**Pull request by jszwedko**
Since the repository changed Github organizations

Fixes #22

### CODE REVIEW

**Comment by gravis** [comment]
FYI, this is a breaking change, with unfortunate issues:

```
2016/06/29 14:56:32 http: panic serving 172.17.0.1:50632: interface conversion: *negroni.responseWriter is not negroni.ResponseWriter: missing method Before
goroutine 9 [running]:
net/http.(*conn).serve.func1(0xc820018a80)
        /usr/local/go/src/net/http/server.go:1389 +0xc1
panic(0x9acc60, 0xc82029b340)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc82026f860, 0x7f4e35db7880, 0xc82029b0c0, 0xc8200e2460, 0xc8202bcf60)
        /go/src/github.com/meatballhat/negroni-logrus/middleware.go:138 +0x619
github.com/codegangsta/negroni.middleware.ServeHTTP(0x7f4e35db7680, 0xc82026f860, 0xc8202bcda0, 0x7f4e35db7880, 0xc82029b0c0, 0xc8200e2460)
        /go/src/github.com/codegangsta/negroni/negroni.go:33 +0xaa
github.com/codegangsta/negroni.(middleware).ServeHTTP-fm(0x7f4e35db7880, 0xc82029b0c0, 0xc8200e2460)
        /go/src/github.com/codegangsta/negroni/negroni.go:33 +0x53
github.com/unrolled/secure.(*Secure).HandlerFuncWithNext(0xc8202ab180, 0x7f4e35db7880, 0xc82029b0c0, 0xc8200e2460, 0xc8202bcf40)
        /go/src/github.com/unrolled/secure/secure.go:116 +0x8e
github.com/unrolled/secure.(*Secure).HandlerFuncWithNext-fm(0x7f4e35db7880, 0xc82029b0c0, 0xc8200e2460, 0xc8202bcf40)
[...]
```

**Comment by jszwedko** [comment]
Hi @gravis!

Unfortunately, I wasn't able to reproduce your issue. Can you post some sample code that exhibits the problem?

**Comment by gravis** [comment]
There you go:

```
package main

import (
        "fmt"
        "net/http"

        log "github.com/Sirupsen/logrus"
        "github.com/codegangsta/negroni"
        "github.com/meatballhat/negroni-logrus"
)

func main() {
        n := negroni.New()

        logMW := negronilogrus.NewMiddlewareFromLogger(log.StandardLogger(), "web") // Use our configured logger
        n.Use(logMW)

        mux := http.NewServeMux()
        mux.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
                fmt.Fprintf(w, "Welcome!")

        })
        n.UseHandler(mux)

        n.Run(":8080")
}
```

It builds, but panics when you hit `/`

**Comment by gravis** [comment]
Note that I use `github.com/codegangsta/negroni`, and that's the issue of course. But we should make sure it doesn't compile for those who haven't switch to urfave repo yet...

**Comment by jszwedko** [comment]
Ah I see it now, because the interface uses itself in one of the function signatures -- that is unfortunate. However, without the change, users that _do_ switch to `urfave/negroni` will suffer the same error. This is an unfortunate side effect of the import path being the same as the remote location that I hadn't considered until now.

Unfortunately, I think it is likely better to encourage users to switch to the new import path for `negroni`, than it is to prohibit it. I'm open to alternatives that could accommodate both, but I can't come up with anything sensible currently.

**Pull request merged**
